/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_yuvdecorder_GL2JNILib */

#ifndef _Included_com_demo_yuvdecorder_GL2JNILib
#define _Included_com_demo_yuvdecorder_GL2JNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_yuvdecorder_GL2JNILib
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_demo_yuvdecorder_GL2JNILib_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_demo_yuvdecorder_GL2JNILib
 * Method:    drawTexture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_demo_yuvdecorder_GL2JNILib_drawTexture
  (JNIEnv *, jclass);

/*
 * Class:     com_demo_yuvdecorder_GL2JNILib
 * Method:    stopDecorde
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_demo_yuvdecorder_GL2JNILib_stopDecorde
  (JNIEnv *, jclass);

/*
 * Class:     com_demo_yuvdecorder_GL2JNILib
 * Method:    pauseDecorde
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_demo_yuvdecorder_GL2JNILib_pauseDecorde
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_demo_yuvdecorder_GL2JNILib
 * Method:    decorde2Show
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_demo_yuvdecorder_GL2JNILib_decorde2Show
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_demo_yuvdecorder_GL2JNILib
 * Method:    yuv2Show
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_demo_yuvdecorder_GL2JNILib_yuv2Show
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
